### ISSUE TITLE
There are some typos

### ISSUE THREAD

**Issue by szepeviktor** [voku/weather#6]
Please see https://github.com/szepeviktor/typos-on-you/actions/runs/5551173399/jobs/10137023895

```
Warning: "Managment" should be "Management".
Warning: "continous" should be "continuous".
Warning: "powerfull" should be "powerful".
Warning: "relly" should be "really".

// build/docs/base.md
Warning: "Managment" should be "Management".
Warning: "continous" should be "continuous".
Warning: "powerfull" should be "powerful".
Warning: "relly" should be "really".
```

`typos` could be [ran in CI](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Continuous-integration-Continuous-delivery-spelling.yml).

**Comment by szepeviktor** [comment]
A copy of README and all of its typos is in `build/docs/base.md`.

**Comment by voku** [comment]
You are right, I placed a comment about the build step in the README itself. 😄

---

fixed, again
